### ISSUE TITLE
**feedback** and **mark** fields per question

### ISSUE THREAD

**Issue by So-Cool** [So-Cool/quick-quiz#7]
Allow **feedback** and **user id** fields per question (what are the marking criteria). Change *user id* field to *candidate number* and allow automatic generation of feedback CSV.

**Comment by willprice** [comment]
Is the `--feedback` flag meant to work? As it current throws an error when I try and generate the `my_quiz.quiz` file: `./resources/compile_quiz.py --feedback my_quiz.quiz`

```
Traceback (most recent call last):
  File "./resources/compile_quiz.py", line 1038, in <module>
    toFeedback( rootDir, uid, results, sectionCoverage, difficulty, quantifiedSections, questionTypes )
  File "./resources/compile_quiz.py", line 699, in toFeedback
    d.append('#' + str(r['number']).zfill(2) + ': ' + r['text'])
KeyError: 'text'
```

**Comment by So-Cool** [comment]
You should only use flags described in the `readme.md` file. The rest is reserved for marking; they are not implemented yet.
